theme: jekyll-theme-minimal
title: TacticalAPI Documentation
description: Documentation and status monitoring for the Tactical AI Discord Bot API
baseurl: "/TacticalAPI"
url: "https://developerhubofficial.github.io"